# Generated by Django 4.2.1 on 2023-05-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_talentedstudents_study_group"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TalentedStudents",
            new_name="ActiveStudents",
        ),
    ]
