# Generated by Django 4.2.1 on 2023-05-15 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_rename_talentedstudents_activestudents"),
    ]

    operations = [
        migrations.CreateModel(
            name="InactiveStudents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("study_group", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="inactive_students/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "tif", "tiff"]
                            )
                        ],
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="activestudents",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="active_students/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "tif", "tiff"]
                    )
                ],
            ),
        ),
    ]
