# Generated by Django 4.2.1 on 2023-05-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("time", models.CharField(max_length=20)),
                ("course", models.CharField(max_length=100)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("AX", "AX"),
                            ("KIF", "KIF"),
                            ("TELEKOM", "TELEKOM"),
                            ("RADIO", "RADIO"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
