# Generated by Django 4.2.1 on 2023-05-13 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("education", models.CharField(max_length=200)),
                ("academic_title", models.CharField(max_length=150)),
                ("specialty", models.CharField(max_length=150)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="teacher_photo/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "tif", "tiff"]
                            )
                        ],
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
