# Generated by Django 4.2.1 on 2023-05-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listeners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listeners",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/listeners/"
            ),
        ),
    ]
